/**
 * Centralized error codes for the XML parser module
 */

export const PARSER_ERRORS = {
  // Common errors
  PARSE_ERROR: "PARSE_ERROR",

  // XML validation
  EMPTY_XML: "EMPTY_XML",
  XML_PARSE_ERROR: "XML_PARSE_ERROR",
  COMPROBANTE_PARSE_ERROR: "COMPROBANTE_PARSE_ERROR",

  // Authorization
  NOT_AUTHORIZED: "NOT_AUTHORIZED",
  MISSING_CLAVE: "MISSING_CLAVE",
  INVALID_CLAVE_FORMAT: "INVALID_CLAVE_FORMAT",
  MISSING_AUTORIZACION: "MISSING_AUTORIZACION",
  INVALID_AUTORIZACION_FORMAT: "INVALID_AUTORIZACION_FORMAT",

  // Document type detection
  UNKNOWN_DOCUMENT_TYPE: "UNKNOWN_DOCUMENT_TYPE",
  UNSUPPORTED_DOCUMENT_TYPE: "UNSUPPORTED_DOCUMENT_TYPE",
  INVALID_FACTURA_STRUCTURE: "INVALID_FACTURA_STRUCTURE",
  INVALID_RETENCION_STRUCTURE: "INVALID_RETENCION_STRUCTURE",
  INVALID_NOTA_CREDITO_STRUCTURE: "INVALID_NOTA_CREDITO_STRUCTURE",
  INVALID_NOTA_DEBITO_STRUCTURE: "INVALID_NOTA_DEBITO_STRUCTURE",
  INVALID_GUIA_REMISION_STRUCTURE: "INVALID_GUIA_REMISION_STRUCTURE",

  // Document fields
  MISSING_CLAVE_ACCESO: "MISSING_CLAVE_ACCESO",
  MISSING_EMISOR_RUC: "MISSING_EMISOR_RUC",
  MISSING_RECEPTOR_ID: "MISSING_RECEPTOR_ID",
  MISSING_DOC_MODIFICADO: "MISSING_DOC_MODIFICADO",
  NO_RETENTIONS: "NO_RETENTIONS",
  NO_DESTINATARIOS: "NO_DESTINATARIOS",
  MISSING_PLACA: "MISSING_PLACA",

  // RUC validation
  MISSING_RUC: "MISSING_RUC",
  INVALID_RUC_FORMAT: "INVALID_RUC_FORMAT",
  INVALID_PROVINCE_CODE: "INVALID_PROVINCE_CODE",
  INVALID_ENTITY_TYPE: "INVALID_ENTITY_TYPE",
  INVALID_RUC_SUFFIX: "INVALID_RUC_SUFFIX",

  // Date validation
  MISSING_DATE: "MISSING_DATE",
  FUTURE_DATE: "FUTURE_DATE",

  // Monetary validation
  INVALID_MONETARY_VALUE: "INVALID_MONETARY_VALUE",
  NEGATIVE_VALUE: "NEGATIVE_VALUE",
} as const;

export type ParserErrorCode =
  (typeof PARSER_ERRORS)[keyof typeof PARSER_ERRORS];
